### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by jnoelEFL** [raisou/worldcupprono#1]
Hi, 
your app looks fun. If you want I can help you maintain it. I am a JS developer, but I do not know much about Python.
Can you tell me how to start the back part so that I can test it?
If you want to keep the project personal, I understand it.
Regards

**Comment by raisou** [comment]
Hello,

This project is a pretext to learn Vuejs in an active way. I made some choices to keep it as fast as possible to build on my personal time.

I don't really want to keep it personal but i don't want to be involved too far. (coz of time available)
That said, it could be cool to have it working for the worldcup time :)

I just added some steps to get you up and running with a local version.
I hope explanations are ok and clear enough.

I created two trello boards (french only) as a "roadmap" for what i have in mind before the initial release or just to declare bugs (but it can be done here aswell).

https://trello.com/b/xe6IOn6b/bugs
https://trello.com/b/x2HPnL8p/am%C3%A9liorations

Anyway, feel free to contribute.

Regards
